### ISSUE TITLE
When exporting NFS, automatic additions to exports missing Linefeed

### ISSUE THREAD

**Issue by ScotchTape** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#10]
applying changes to a NFS share, /etc/export breaks at ZFS Automatic exports:

Due to Markdown, I've uploaded the messages to [Pastebin](http://pastebin.com/Tt3E3rw9)

`Error #4000:
exception 'OMVException' with message 'Failed to execute command 'export LANG=C; systemctl start nfs-kernel-server 2>&1': Job for nfs-kernel-server.service failed. See 'systemctl status nfs-kernel-server.service' and 'journalctl -xn' for details.' in /usr/share/php/openmediavault/systemctl.inc:64
Stack trace:
#0 /usr/share/php/openmediavault/systemctl.inc(83): OMVSystemCtl->exec('start', false)
#1 /usr/share/openmediavault/engined/module/nfs.inc(84): OMVSystemCtl->enable(true)
#2 /usr/share/openmediavault/engined/rpc/config.inc(206): OMVModuleNfs->startService()
#3 [internal function]: OMVRpcServiceConfig->applyChanges(Array, Array)
#4 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#5 /usr/share/php/openmediavault/rpcservice.inc(158): OMVRpcServiceAbstract >callMethod('applyChanges', Array, Array)
#6 /usr/share/openmediavault/engined/rpc/config.inc(224): OMVRpcServiceAbstract->callMethodBg('applyChanges', Array, Array)
#7 [internal function]: OMVRpcServiceConfig->applyChangesBg(Array, Array)
#8 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#9 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('applyChangesBg', Array, Array)
#10 /usr/sbin/omv-engined(500): OMVRpc::exec('Config', 'applyChangesBg', Array, Array, 1)
#11 {main}`

resulting /etc/exports:

`/export/Movies 192.168.178.14(rw,all_squash,subtree_check,insecure,fsid=1,anonuid=1000,anongid=100)
/export/Shows 192.168.178.14(rw,all_squash,subtree_check,insecure,fsid=2,anonuid=1000,anongid=100)
# NFSv4 - pseudo filesystem root

/export 192.168.178.14(ro,fsid=0,root_squash,no_subtree_check,hide)
# ZFS automatic exports

"/export/Movies/Movies" 192.168.178.14(rw,all_squash,subtree_check,insecure,fsid=1,anonuid=1000,anongid=100,nohide)"/export/Movies/Shows" 192.168.178.14(rw,all_squash,subtree_check,insecure,fsid=1,anonuid=1000,anongid=100,nohide)"/export/Shows/Movies" 192.168.178.14(rw,all_squash,subtree_check,insecure,fsid=2,anonuid=1000,anongid=100,nohide)"/export/Shows/Shows" 192.168.178.14(rw,all_squash,subtree_check,insecure,fsid=2,anonuid=1000,anongid=100,nohide)`

Support-info:

`================================================================================
# = OS/Debian information

Distributor ID: debian
Description: Debian GNU/Linux 8 (jessie)
Release: 8.3
Codename: jessie
# 
# = openmediavault information

Release: 3.0.13
Codename: Erasmus
# 
# = Date

So 20. Mär 10:41:35 CET 2016
# 
# = Locale

en_US.UTF-8
# 
# = System information

Linux nas-mopped 4.3.0-0.bpo.1-amd64 #1 SMP Debian 4.3.5-1~bpo8+1 (2016-02-23) x86_64 GNU/Linux

================================================================================`

Package:

`dpkg -s openmediavault-zfs

Package: openmediavault-zfs
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 332
Maintainer: OpenMediaVault Plugin Developers plugins@omv-extras.org
Architecture: amd64
Version: 3.0.0
Depends: openmediavault (>= 1.7), debian-zfs (>= 0.6.5), build-essential
Description: OpenMediaVault plugin for ZFS`

**Comment by luxflow** [comment]
cannot reproduce in OMV 3.X, fixed
