### ISSUE TITLE
installation issue on OMV3

### ISSUE THREAD

**Issue by fumantsu** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#11]
I'm getting this:

Setting up debian-zfs (7~jessie) ...
Setting up openmediavault-zfs (3.0.0) ...
modprobe: FATAL: Module zfs not found.
dpkg: error processing package openmediavault-zfs (--configure):
subprocess installed post-installation script returned error exit status 1

installed packages:
zfs-initramfs
zfs-dracut
zfsonlinux
zfs-modules-source
openmediavault-zfs
zfsnap
zfsutils
libguestfs-zfs
debian-zfs
zfs-dbg
zfs-fuse
libzfs-dev
zfs-dkms
libzfs2

Any help?

**Comment by ryecoaaron** [comment]
My best advice would to not use OMV 3 yet.  It is not ready and will be going through a major change soon that may break a lot of things.

**Comment by fumantsu** [comment]
I'm only testing in a VM trying to simulate the original OVM 2 installation. No production yet :D

**Comment by nicjo814** [comment]
How did you go about installing it? Did you install omv extras and then the plug-in from there? 
//Niclas

**Comment by fumantsu** [comment]
I install the extras plugin, apt-get upgrade (upgrades also to some zfs packages) restart and then from gui I install a batch of plugins.

**Comment by fumantsu** [comment]
The latest packages (zfs-utils etc) are working now. I just test them and are working. So I will close the issue.
