### ISSUE TITLE
New pool by-id created with device names

### ISSUE THREAD

**Issue by fumantsu** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#12]
Hello,

I test creating a pool (in a VM) using id as device alias but the pool was created by device path.
Pool status (zpool status):

  pool: pool
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	pool        ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sdb     ONLINE       0     0     0
	    sdc     ONLINE       0     0     0

The test I made is on OMV 3.x and I don't know if is applicable to OMV 2.x
If I can get some operational logs for the plugin just point me to them.

**Comment by luxflow** [comment]
I think this was fixed,
or this is due to using omv-zfs on virtual machine
If you encounter again, reopen issue
