### ISSUE TITLE
Problem installing in OMV3.0 (in a KVM guest)

### ISSUE THREAD

**Issue by marcal** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#14]
Hello,

I have tried to install OMV 3.0 in a virtual machine and I can't install the ZFS plugin.

All is fine till the end where I have the error message 
```
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for initramfs-tools (0.120+deb8u2) ...
update-initramfs: Generating /boot/initrd.img-4.5.0-0.bpo.2-amd64
W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
W: mdadm: no arrays defined in configuration file.
```
```

>>> *************** Error ***************
Failed to connect to socket: No such file or directory
<<< *************************************

```
After that, I can't login anymore to the webgui.
If I do the command  

`omv-engined -d -f `

(seen from a thread about this error) I have the following error

`PHP Fatal error:  require_once(): Failed opening required 'openmediavault/object.inc' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/openmediavault/engined/rpc/zfs.inc on line 19
`

The only way to make the GUI work again is 

`apt-get remove zfs*`

**Comment by ryecoaaron** [comment]
The zfs plugin currently only works with OMV <= 3.0.13.  You will either have to go back to OMV 2.x or wait until the zfs plugin is ported to the latest OMV version.
