### ISSUE TITLE
OMV3 - zpool with zvol is not opening the zfs category

### ISSUE THREAD

**Issue by fumantsu** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#16]
Hello, 
I'm testing the zfs plugin and I have a pool with one zvol. When I'm clicking in the category and waiting fs/vols to be present I'm getting this error message.

Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; zfs get all | grep tank0/VM_Datastore@ 2>&1' with exit code '1': tank0/VM_Datastore	330G	1.73T	19.9G	-
Error #0:
exception 'OMV\ExecException' with message 'Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; zfs get all | grep tank0/VM_Datastore@ 2>&1' with exit code '1': tank0/VM_Datastore	330G	1.73T	19.9G	-' in /usr/share/php/openmediavault/system/process.inc:174
Stack trace:
#0 /usr/share/omvzfs/Zvol.php(369): OMV\System\Process->execute(Array, 1)
#1 /usr/share/omvzfs/Zvol.php(80): OMVModuleZFSZvol->exec('zfs get all | g...', Array, 1)
#2 /usr/share/omvzfs/Utils.php(429): OMVModuleZFSZvol->__construct('tank0/VM_Datast...')
#3 /usr/share/openmediavault/engined/rpc/zfs.inc(194): OMVModuleZFSUtil::getZFSFlatArray()
#4 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#6 /usr/share/php/openmediavault/rpc/rpc.inc(84): OMV\Rpc\ServiceAbstract->callMethod('getObjectTree', Array, Array)
#7 /usr/sbin/omv-engined(516): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 1)
#8 {main}

**Comment by luxflow** [comment]
fixed in 3.0.3.5 
3.0.3.5 will be uploaded soon
