### ISSUE TITLE
Add dependency for the kernel version

### ISSUE THREAD

**Issue by fumantsu** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#17]
Hi,

I don't know if it is possible to be added to this plugin or to the backport kernels (especially for OMV3). Kernels 4.7+ are not compatible with zfs 0.6.5.7 so when was available this kernel in the backports it was breaking the zfs and of course the plugin.
The support for kernels 4.7 (I guess also 4.8 based on this https://github.com/zfsonlinux/zfs/pull/5025) has been added to 0.6.5.8 but I'm wondering if there is a way since plugin is coming together with the new zfs versions to put a dependecy control.

**Comment by luxflow** [comment]
http://forum.openmediavault.org/index.php/Thread/7633-HOWTO-Instal-ZFS-Plugin-use-ZFS-on-OMV/?postID=126527#post126527
from omv-zfs version 3.0.4, 4.7 kernel is already supported 
checkout this http://forum.openmediavault.org/index.php/Thread/7633-HOWTO-Instal-ZFS-Plugin-use-ZFS-on-OMV/?postID=126527#post126527
