### ISSUE TITLE
zfsutils dependency

### ISSUE THREAD

**Issue by sanmadjack** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#18]
Was compiling 3.0.4 for use on my debian jessie server, using the official zfs repos. This plugin's set to depend on zfsutils-linux by default, but the package is just zfsutils in the official repo. I manually changed it in my build, but can it be set up as an alternate dependency?

**Comment by luxflow** [comment]
Can I ask why you want to use zfsutils im zfs repo?

**Comment by ryecoaaron** [comment]
I added it as an alternative dependency.  Just to be clear, omv-extras enables the "official" dependencies.

**Comment by sanmadjack** [comment]
Because I want to use the official releases from the zfsol team? I probably would have ended up with the official dependencies but due to openmediavault-zfs not being available in the OMV 3.0 extras repos at the moment, I've been setting up some things manually. I figured that it would probably be a good idea to update the dependency to allow the option of using the official repos. At minimum, it couldn't hurt?

**Comment by sanmadjack** [comment]
Thanks @ryecoaaron , that's super cool

**Comment by luxflow** [comment]
it couldnt hurt anything if you use 3.x kernel (current zfs repo dosnt support 4.x)
currently debian repo one is more up to date package than zfs repo
and since they use same source, i dont think they are different
anyway it is free to use anything

**Comment by ryecoaaron** [comment]
Is there a more "official" repo than this?
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/etc/omvextras/default_repos.xml#L87

**Comment by sanmadjack** [comment]
I don't think so, that's what I'm using. The debain-zfs package from that server depends on zfsutils, not zfsutils-linux. From what I see, zfsutils-linux comes from the debian repos not the zfs repos, at least that's what my apt-cache tells me.

**Comment by ryecoaaron** [comment]
Just a note... I noticed that proxmox actually installs zfsutils AND zfsutils-linux

dpkg -l | grep zfsutils
ii  zfsutils                       0.6.5.8-pve12~bpo80            all          transitional package
ii  zfsutils-linux                 0.6.5.8-pve12~bpo80            amd64        command-line tools to manage OpenZFS filesystems

**Comment by sunhort** [comment]
Fresh problems on deb 11 was solved by doing `apt install zfsutils-linux/bullseye-backports`, bullseye-backports was added to sources.list before doing that

**Comment by ryecoaaron** [comment]
If you have backports enabled (can be done with omv-extras), omv-extras should pin all zfs* backports packages and then the backports version would be installed when installing the plugin.  Installing the proxmox kernel allows you to disable the backports repo if you would like.

**Comment by sunhort** [comment]
Nope, it didn't work that way with my 5.14 kernel. Deb 11 is pretty fresh thing and OMV will have issues with it for long time. Only smoking original debian manuals helped me to resolve dependency issue. Double check this on your testing machine please, if you want to help in future.

**Comment by ryecoaaron** [comment]
You are doing too many manual things and/or not using the proxmox kernel.  The 5.14 kernel is not the proxmox kernel.  And I am running this on three machines with the proxmo 5.15 kernel including my primary home server.

**Comment by sunhort** [comment]
Tested proxmox kernel: 
update-initramfs: Generating /boot/initrd.img-5.15.7-1-pve
Errors were encountered while processing:
 zfs-dkms
I guess it's not compatible as installing zfs-dkms from cli (not from omv webgui) returned: 
Building initial module for 5.15.7-1-pve
configure: error:
        *** None of the expected "capability" interfaces were detected.
        *** This may be because your kernel version is newer than what is
        *** supported, or you are using a patched custom kernel with
        *** incompatible modifications.
        ***
        *** ZFS Version: zfs-2.0.3-9
        *** Compatible Kernels: 3.10 - 5.10
Error! Bad return status for module build on kernel: 5.15.7-1-pve (x86_64)

I guess will stay on 5.14

**Comment by ryecoaaron** [comment]
Remove zfs-dkms and dkms because the zfs module is already builtin to the proxmox kernel.  I have been recommending the zfs kernel for years because of this.  The zfs module has to be compiled for debian kernels and is very picky about dependencies.

**Comment by ryecoaaron** [comment]
Transmission is better in docker anyway.  I can only maintain so many plugins as well.

And OMV will not be more tolerant of desktops.  It actually has conflict statements now.  You can run a destkop in docker if you need to login to the box.  RPis are cheap enough that you do not need a desktop running all the time on the omv box.  That is a discussion for the forum not this issue.  And there are plenty of threads on it.
