### ISSUE TITLE
Object details view textarea doesn't grow and is too short.

### ISSUE THREAD

**Issue by ikogan** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#2]
When looking up the details of an object in either Firefox or Chrome, the textarea that displays command output seems to not grow ever and thus remain too short:

![capture](https://cloud.githubusercontent.com/assets/1840337/9830486/304c94f6-58fe-11e5-842d-639a6945c8b0.PNG)

**Comment by nicjo814** [comment]
I've pushed a fix for that which works fine here. Can you test?

**Comment by ikogan** [comment]
After discussion at https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/08b903b437106525c20b88573d6d67fa77853ac5, https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/49939c39a679334e93901d63725db01d9b89b00d works great.
