### ISSUE TITLE
Error creating new pool (OMV 3.0.59 on Proxmox 4.3 VM)

### ISSUE THREAD

**Issue by hillsy** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#20]
I'm evaluating OMV at work for a ZFS-backed NFS & iSCSI server (I already use it at home in a different configuration).

I've installed it on our Proxmox VE 4.3 cluster and added some data disks. When I try to create a new ZFS pool I get the attached error.

The error seems to be the same whether I use the backports kernel or the PVE kernel.
![screenshot at 2017-01-04 16 32 46](https://cloud.githubusercontent.com/assets/770580/21651053/1933e776-d29f-11e6-9711-be2d6306d915.png)

**Comment by luxflow** [comment]
try changing driver alias other than by Id, as I know virtualized hard disk (vda) have issues that doesn't show in /dev/disk/by-id/

**Comment by hillsy** [comment]
"By path" fails, "None" appears to succeed (a pool is created at least, I haven't tried doing much with it yet)

**Comment by ryecoaaron** [comment]
I didn't have any problem creating a 4 drive mirror pool on 3.0.59 running on Proxmox 4.4 using by-id.  I used the same settings from your screenshot.

**Comment by luxflow** [comment]
maybe those drive driver isn't virtio or pci passthrough (SAS HBA), I think

**Comment by hillsy** [comment]
Here's the VM hardware setup. 

We don't have any nodes on PVE 4.4 yet. If/when we do I'll see if the problem remains.
![screenshot_2017-01-05_14-53-48](https://cloud.githubusercontent.com/assets/770580/21684861/447b8a16-d357-11e6-9ae9-dc91f032e4f2.png)

**Comment by ryecoaaron** [comment]
I wouldn't think the pve 4.3 vs 4.4 issue would cause this but not sure.  Your setup looks about the same other than you used scsi for the OS drive.  Is the VM running the latest OMV 3.x?

**Comment by luxflow** [comment]
it is due to virtio, I tested it, virtio driver doesn't show in by-disk by-path
