### ISSUE TITLE
Add acltype property

### ISSUE THREAD

**Issue by Skaronator** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#23]
Add acltype property and set it to "posixacl" to allow ACL by default.

Ref: http://forum.openmediavault.org/index.php/Thread/13554-Error-changing-ACL-permissions-Failed-to-execute-command-Operation-not-supported/

**Comment by luxflow** [comment]
thanks for reporting
I agree to add acltype property, but I'm not sure to set it posixacl by default (stability? compatiblity in other zfs system such as freebsd)
so I will only add acltype,xattr property in next version

**Comment by Skaronator** [comment]
Alright thanks!

fixed via https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/bcc06ea6d337169fd2f51dd3c2323bc5c687ad82
