### ISSUE TITLE
Scrub: Add pause and abort button when scrub is in progress

### ISSUE THREAD

**Issue by Skaronator** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#24]
When a current scrub is already running and you press Scrub again in the Webinterface you'll get following error:

```
Fehler #0:
exception 'OMV\ExecException' with message 'Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; zpool scrub "StorageZFS"' with exit code '1': ' in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/omvzfs/Utils.php(395): OMV\System\Process->execute(Array, 1)
#1 /usr/share/omvzfs/Zpool.php(370): OMVModuleZFSUtil::exec('zpool scrub "St...', Array, 1)
#2 /usr/share/openmediavault/engined/rpc/zfs.inc(591): OMVModuleZFSZpool->scrub()
#3 [internal function]: OMVRpcServiceZFS->scrubPool(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#5 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('scrubPool', Array, Array)
#6 /usr/sbin/omv-engined(522): OMV\Rpc\Rpc::call('ZFS', 'scrubPool', Array, Array, 1)
#7 {main}
```

### Instead it should simply say, that there is already a Scrubbing progress.

I was confused because of this error so I just tried to call `zpool scrub "StorageZFS"` and got this response:  `cannot scrub StorageZFS: currently scrubbing; use 'zpool scrub -s' to cancel current scrub` which was way more helpfull than the error above.

**Comment by Skaronator** [comment]
Also some progress or info's about the scrub progress would be good. The mdadm Raid in the OMV Webinterface report about checking, rebuilding, rebuild time/percentage etc. but ZFS doesn't.

For example:
```
root@OMV-NAS:/StorageZFS# zpool status StorageZFS
  pool: StorageZFS
 state: ONLINE
  scan: scrub in progress since Fri Feb 24 12:04:23 2017
    6,73T scanned out of 13,1T at 289M/s, 6h28m to go
    164K repaired, 51,23% done
config:

        NAME                                   STATE     READ WRITE CKSUM
        StorageZFS                             ONLINE       0     0     0
          raidz1-0                             ONLINE       0     0     0
            ata-HGST_HDN728080ALE604_VLKJJ1EY  ONLINE       0     0     0
            ata-HGST_HDN728080ALE604_VLKJU6EY  ONLINE       0     0     0  (repairing)
            ata-HGST_HDN728080ALE604_VLKJDW9Y  ONLINE       0     0     0
            ata-HGST_HDN728080ALE604_VLKJA4MY  ONLINE       0     0     0

errors: No known data errors
```

**Comment by luxflow** [comment]
I'll be busy for the next 6 months (maybe 1 year), I cannot patch anymore
maybe other developer help

**Comment by Skaronator** [comment]
@luxflow What is the best practice to develop/work on Plugins in OMV? I know PHP and a bit JS.

**Comment by luxflow** [comment]
http://forum.openmediavault.org/index.php/Thread/15285-DIY-Plugin-Guide-for-3-x-Beta/
good startpoint
for me I learned commit by commit from other plugins which has similar function and UI

**Comment by Skaronator** [comment]
Since ZoL 0.7.0 is it possible to pause a scrub so it would be a better solution to hide the scrub button and make 2 new buttons "Pause Scrub" and "Cancel Scrub"

**Comment by ryecoaaron** [comment]
Closing due to age.
