### ISSUE TITLE
The data model 'rpc.zfs.exportpool' does not exist.

### ISSUE THREAD

**Issue by disrupted** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#26]
when trying to expand my existing Mirror to RAIDZ1 by adding an additional hard drive I receive this error message (OMV 3.0.74 + **openmediavault-zfs 3.0.16** package):
`Fehler #0: exception 'OMV\Exception' with message 'The data model 'rpc.zfs.exportpool' does not exist.' in /usr/share/php/openmediavault/datamodel/manager.inc:149 Stack trace: #0 /usr/share/php/openmediavault/rpc/paramsvalidator.inc(42): OMV\DataModel\Manager->getModel('rpc.zfs.exportp...') #1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(169): OMV\Rpc\ParamsValidator->__construct('rpc.zfs.exportp...') #2 /usr/share/openmediavault/engined/rpc/zfs.inc(432): OMV\Rpc\ServiceAbstract->validateMethodParams(Array, 'rpc.zfs.exportp...') #3 [internal function]: OMVRpcServiceZFS->expandPool(Array, Array) #4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array) #5 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('expandPool', Array, Array) #6 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('ZFS', 'expandPool', Array, Array, 1) #7 {main}`

**Comment by ryecoaaron** [comment]
Fixed in 3.0.18

**Comment by disrupted** [comment]
can't confirm sadly
