### ISSUE TITLE
Graphs don't work on Filesystem

### ISSUE THREAD

**Issue by Skaronator** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#28]
![image](https://user-images.githubusercontent.com/2886913/31951078-69f28d78-b8dd-11e7-844e-b32421448dbc.png)

![image](https://user-images.githubusercontent.com/2886913/31951125-89cda93e-b8dd-11e7-9e70-a125d8316069.png)

**Comment by ryecoaaron** [comment]
closing due to age.
