### ISSUE TITLE
No way to remove a ZFS custom property once it's added

### ISSUE THREAD

**Issue by ikogan** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#3]
According to the docs, you need to run `zfs inherit property object`. It doesn't look like there's any way to do that through the UI?

**Comment by nicjo814** [comment]
In the "Edit properties" dialog of an Object you can inherit the setting. It's in the column furthets to the right. Doing this will delete the user property.

**Comment by ikogan** [comment]
Oh right! I did that before but apparently forgot about that. I must be crazy.

**Comment by theking2** [comment]
There is no "inherit" settings in the dialog:

![Image](https://github.com/user-attachments/assets/6ba1b09b-dfab-44eb-a510-9e73a3cbf6c5)
