### ISSUE TITLE
OMV 4.11 - zfs module cannot be build

### ISSUE THREAD

**Issue by p-bo** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#31]
This is from second attempt, with spl and spl-dkms packages installed beforehand due this message during first attempt:

configure: error: 
	*** Please make sure the kmod spl devel <kernel> package for your
	*** distribution is installed then try again.  If that fails you
	*** can specify the location of the spl objects with the
	*** '--with-spl-obj=PATH' option.

Logs attached:

[apt.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/files/1502538/apt.log)
[build.log](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/files/1502539/build.log)

**Comment by ryecoaaron** [comment]
It is well known (read zfs threads on forum) that the zfs module doesnt compile against the 4.13 kernel. I built the zfs 0.7.3 packages from Debian Sid and put them in the omv-extras testing repo.

**Comment by ryecoaaron** [comment]
The 0.7.3 module does build against the 4.13 kernel.

**Comment by p-bo** [comment]
Yes, it works!
(during compilation red thread and understand from your communication with community member "Skaronator")
Thanks :)
