### ISSUE TITLE
plugin fails to load, compile against latest zfs on linux release?

### ISSUE THREAD

**Issue by nexus76** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#32]
hello,

I'm not using the latest debian repo version of zfs but the zfs on linux source.
building openmediavault-zfs plugin works properly but it doesn't work with zfs-0.7.3 and quits with 
error 127, here's what I get at the commandline by executing commands:

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; zpool status -v "tank"

zpool: Symbol `spa_feature_table' has different size in shared object, consider re-linking
zpool: symbol lookup error: zpool: undefined symbol: thread_init

and here's what I get at the OMV ZFS plugin panel:

`Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; zpool status -v "tank"' with exit code '127':  in /usr/share/php/openmediavault/system/process.inc:175
Stack trace:
#0 /usr/share/omvzfs/Utils.php(398): OMV\System\Process->execute(Array, 127)
#1 /usr/share/omvzfs/Zpool.php(490): OMVModuleZFSUtil::exec('zpool status -v...', Array, 127)
#2 /usr/share/omvzfs/Zpool.php(78): OMVModuleZFSZpool->assemblePool('tank')
#3 /usr/share/omvzfs/Utils.php(243): OMVModuleZFSZpool->__construct('tank')
#4 /usr/share/openmediavault/engined/rpc/zfs.inc(181): OMVModuleZFSUtil::getZFSFlatArray()
#5 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getObjectTree', Array, Array)
#8 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 1)
#9 {main}`

is there a fix for this issue?

kind regards

**Comment by ryecoaaron** [comment]
What version of OMV?  I guess I don't understand how you can use zfs from Debian but the source from ZoL?  The 0.7.3 packages are in the omv-extras testing repo for OMV 4.x and working fine.

**Comment by nexus76** [comment]
Hi, 

OMV 4.0.12-1 (Arrakis)
I'm not using the debian version of zfs which is Version: 0.6.5.11-1,
so I compiled 
spl_0.7.3-1 and 
zfs-dkms_0.7.3-1 from
 https://anonscm.debian.org/git/pkg-zfsonlinux/spl.git
 https://anonscm.debian.org/git/pkg-zfsonlinux/zfs.git

**Comment by ryecoaaron** [comment]
If you just enable the omv-extras testing repo, you will get the 0.7.3 packages that work.
