### ISSUE TITLE
Can't read zfs details

### ISSUE THREAD

**Issue by donhwy** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#34]
![image](https://user-images.githubusercontent.com/31188495/34320757-02339dca-e7be-11e7-9471-4aa0e5331e0f.png)

Too much opacity? Can almost read it.

**Comment by ryecoaaron** [comment]
This has been an issue with any text set to readonly for a long time.  This was fixed in OMV 4.x here - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/e1dbac111e61f2655ddc7d446bb35f6c93f46695

**Comment by belierzz** [comment]
Looks still the same to me in OMV 4.x.

**Comment by artiomn** [comment]
Yes, I have noticed it too.

**Comment by ryecoaaron** [comment]
This was fixed in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/e1dbac111e61f2655ddc7d446bb35f6c93f46695
