### ISSUE TITLE
Shared folders don't find the pool after import/export or reboot with LUKS. UUID is changed

### ISSUE THREAD

**Issue by tueftler0** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#36]
If you import and export a ZFS dataset, or make a reboot with LUKS encrypted HDDs, you can't use your made shared folders anymore.
It looks like the UUID of the ZFS pool have get another number.
The "Device" in Shared folders are showing only a "n/a" and a access to the files are not possible.

Edit on the shared folder, the OS display these error message:
"Failed to execute XPath query '//system/fstab/mntent[uuid='75090a7b-0..."

It could not be, that you have to renew all the shared folders incl. privileges after a reboot.

Please fix that issue - It's real a high prio problem i think.
Could not access the data now. Anybody can give me a tip how to fix that temporary?

Thank you in advanced.

**Comment by subzero79** [comment]
This is a bad combination at the moment. I have in my repository a fork of luks encryption that has a more advanced configuration. I wrote more description here.
 
https://github.com/gandalfb/openmediavault-full-disk-encryption/issues/1#issuecomment-357499137

You can try the other way if it works. Unencrypted zpool, create zvols encrypt then and mount them. If you’re in omv4 you will still have problems with /sharedfolders units.

**Comment by tueftler0** [comment]
Hi there.

Thank you for your answer.
I'll have a look how i can implement your fork into my system.
But first, i have to simulate the ZFS encryption now as you've wrote.

Did you have an idea how to change the made allocation of the share folders to the new UUID?
Otherwise i have around 30 shared folders to change...

**Comment by subzero79** [comment]
My fork should be fine using luks then zfs. It just stops everything until drives are decrypted. 

The problem seems like you lost a mntent entry. A shared folder must be looking for it. Once pool is decrypted try to import it. The new mntent entry for zfs will have an internal uuid. All shared folders must be looking for the old one, replace the common sf uuid <mnentref> into the mntent uuid

**Comment by tueftler0** [comment]
Ok i'll have a look.

> If you’re in omv4 you will still have problems with /sharedfolders units.

Should i go to the actual OMV3 stable to prevent these situations?

**Comment by subzero79** [comment]
Yes. Back to 3 there is no /sharedfolders. The fork also takes care of a those.

**Comment by tueftler0** [comment]
Same problem in 3.0.96 :(
Further tests in progress

**Comment by tueftler0** [comment]
Could you please advice me how to get your fork to the OMV data system?
If i login via SSH with root, "ls" will don't show me anything...

**Comment by subzero79** [comment]
YOu need to clone the repository and build the package
