### ISSUE TITLE
"mountpoint not unique" on zfs-booted machine

### ISSUE THREAD

**Issue by birnbacs** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#38]
I have a Debian machine that boots from a zpool on a pair of mirreored 1TB disks.
A third disk of 4TB disk with zpool 'ariadne' is available for sharing:

```
zfs list
NAME                 USED  AVAIL  REFER  MOUNTPOINT
ariadne              312K  3,51T    96K  /mnt/ariadne
rpool               5,37G   894G    96K  /
rpool/ROOT           887M   894G    96K  none
rpool/ROOT/debian    887M   894G   816M  /
rpool/home           528K   894G    96K  /home
rpool/home/develop   108K   894G   108K  /home/develop
rpool/home/root      204K   894G   204K  /root
rpool/home/seb       120K   894G   120K  /home/seb
rpool/srv            100K   894G   100K  /srv
rpool/swap          4,25G   898G    64K  -
rpool/var            259M   894G    96K  /var
rpool/var/cache      256M   894G   256M  /var/cache
rpool/var/log       1,24M   894G  1,24M  /var/log
rpool/var/spool      712K   894G   712K  /var/spool
rpool/var/tmp        128K   894G   128K  /var/tmp

```

 Now, whenever I select the ZFS plugin it gives me this error:

```
The configuration object 'conf.system.filesystem.mountpoint' is not unique. An object with the property 'dir' and value '/' already exists.

Error #0: OMV\AssertException: The configuration object 'conf.system.filesystem.mountpoint' is not unique. An object with the property 'dir' and value '/' already exists. in /usr/share/php/openmediavault/config/database.inc:495 
Stack trace: 
#0 /usr/share/openmediavault/engined/rpc/fstab.inc(119): OMV\Config\Database->assertIsUnique(Object(OMV\Config\ConfigObject), 'dir') 
#1 [internal function]: OMVRpcServiceFsTab->set(Array, Array) 
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array) 
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array) 
#4 /usr/share/omvzfs/Utils.php(209): OMV\Rpc\Rpc::call('FsTab', 'set', Array, Array) 
#5 /usr/share/openmediavault/engined/rpc/zfs.inc(187): OMVModuleZFSUtil::fixOMVMntEnt(Array) 
#6 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array) 
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array) 
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getObjectTree', Array, Array) 
#9 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 1) 
#10 {main}
```

It seems that every time I use OMV a new <mntent> is appended to the config.xml - which fails as  the dir value is always the same. Whenever I delete such an entry, a new one pops in:

```      
<mntent>
        <uuid>b63450e7-4c63-43e4-aefc-262d57d28e90</uuid>
        <fsname>rpool</fsname>
        <dir>/</dir>
        <type>zfs</type>
        <opts>rw,relatime,xattr,noacl</opts>
        <freq>0</freq>
        <passno>0</passno>
        <hidden>1</hidden>
</mntent>
```

One strange thing is that the UUIDs change each time but are not familiar, that is to say they cannot be found under /dev/disk/...

Why does OMV keep inserting entries?
How can I set the list of zfs pools straight?
Does this behaviour have to do with the existing ZFS pools at all?
Is booting from ZFS a problem here?

Oh, almost forgot:
```
dpkg -l | grep openmediavault
ii  openmediavault                  4.1.0-1                        all          openmediavault - The open network attached storage solution
ii  openmediavault-keyring          1.0                            all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg     4.1.2                          all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-zfs              4.0.1-1                        amd64        OpenMediaVault plugin for ZFS
```

**Comment by artiomn** [comment]
Is it still actual?

**Comment by artiomn** [comment]
I think, package was built and upgraded about a day ago.

**Comment by birnbacs** [comment]
The issue is resolved. Good job and the warmest thanks!
Is there any place for a small donation for the development team?

2018-04-13 15:05 GMT+02:00 Артём <notifications@github.com>:

**Comment by artiomn** [comment]
IDK, but I think, you need to ask @votdev or @ryecoaaron about this.

**Comment by subzero79** [comment]
@birnbacs please read the last comment https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/pull/40 i need some feedback as this fix broke other function and the submitter hasn't replied yet.

**Comment by artiomn** [comment]
Ok.

**Comment by ambiadnb** [comment]
Hello,

it seems that the issue has come back at least I get the same error message again when I access the plugin:
```
The configuration object 'conf.system.filesystem.mountpoint' is not unique. An object with the property 'dir' and value '/boot' already exists.
```
```
Error #0:
OMV\AssertException: The configuration object 'conf.system.filesystem.mountpoint' is not unique. An object with the property 'dir' and value '/boot' already exists. in /usr/share/php/openmediavault/config/database.inc:513
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/fstab.inc(121): OMV\Config\Database->assertIsUnique(Object(OMV\Config\ConfigObject), 'dir')
#1 [internal function]: Engined\Rpc\FsTab->set(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array)
#4 /usr/share/omvzfs/Utils.php(217): OMV\Rpc\Rpc::call('FsTab', 'set', Array, Array)
#5 /usr/share/openmediavault/engined/rpc/zfs.inc(186): OMVModuleZFSUtil::fixOMVMntEnt(Array)
#6 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getObjectTree', Array, Array)
#9 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 1)
#10 {main}
```

I have the following zfs datasets configured:
```
NAME                        USED  AVAIL     REFER  MOUNTPOINT
bpool                      83.7M  1.67G       96K  /boot
bpool/BOOT                 82.9M  1.67G       96K  none
bpool/BOOT/debian          82.8M  1.67G     82.8M  /boot
dpool                      1.71M  7.04T      128K  none
dpool/DATA                  490K  7.04T      128K  none
dpool/DATA/nas              362K  7.04T      128K  /srv/nas
rpool                      1.21G   104G       96K  /
rpool/ROOT                 1.15G   104G       96K  none
rpool/ROOT/debian          1.15G   104G     1.15G  /
rpool/home                  456K   104G       96K  /home
rpool/home/root             232K   104G      232K  /root
rpool/opt                    96K   104G       96K  /opt
rpool/srv                  1.75M   104G     1.75M  /srv
rpool/tmp                   156K   104G      156K  /tmp
rpool/usr                   224K   104G       96K  /usr
rpool/usr/local             128K   104G      128K  /usr/local
rpool/var                  55.3M   104G       96K  /var
rpool/var/cache            47.2M   104G     47.2M  /var/cache
rpool/var/lib                96K   104G       96K  /var/lib
rpool/var/log              1.68M   104G     1.68M  /var/log
rpool/var/mail               96K   104G       96K  /var/mail
rpool/var/snap               96K   104G       96K  /var/snap
rpool/var/spool             692K   104G      692K  /var/spool
rpool/var/tmp               120K   104G      120K  /var/tmp
rpool/var/www              5.16M   104G     5.16M  /var/www
spool                      11.2G   476M       96K  /spool
spool/swap                 11.2G  11.6G       76K  -
```

And I have the following open media vault packages installed:
```
ii  openmediavault                     5.5.23-1                            all          openmediavault - The open network attached storage solution
ii  openmediavault-apttool             3.6                                 all          apt tool plugin for OpenMediaVault.
ii  openmediavault-autoshutdown        5.1.6                               all          OpenMediaVault AutoShutdown Plugin
ii  openmediavault-diskstats           5.0.7-1                             all          openmediavault disk monitoring plugin
ii  openmediavault-downloader          5.1                                 all          OpenMediaVault downloader plugin
ii  openmediavault-keyring             1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-locate              3.5                                 all          locate plugin for OpenMediaVault.
ii  openmediavault-lvm2                5.0.2-1                             all          openmediavault Logical Volume Manager (LVM2) plugin
ii  openmediavault-omvextrasorg        5.4.5                               all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-resetperms          5.0                                 all          Reset Permissions
ii  openmediavault-sharerootfs         5.0.2-1                             all          openmediavault share root filesystem plugin
ii  openmediavault-symlinks            3.1.5                               all          OpenMediaVault symlinks plugin
ii  openmediavault-zfs                 5.0.5                               amd64        OpenMediaVault plugin for ZFS
```

Any help would be much appreciated.
Thank you in advance.

**Comment by drgrandios** [comment]
I can confirm this - a fresh Debian install on mirrored ZFS (based on the "standard" installation instruction: https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Bullseye%20Root%20on%20ZFS.html ) plus OMV 6 + ZFS plugin throws this error.

The old working fix, done by this commit:

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/pull/40/commits/f4b93081eefc68a4c52342b2faef33c446f70f54

has been broken by this commit:

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/dd2245ad5552b8345403ae61ccfe94ebf8f9f523

I changed the affected line in Utils.php back to the version described in the inital fix. This works for me...

```php
if (($mntpoint != "none") && ($mntpoint !== "legacy") && strpos($name, '/')) {
```

**Comment by ryecoaaron** [comment]
Using strpos doesn't make sense.  It will return 0 (false) for any mountpoint that starts with / and not import it. All we want to avoid importing is a pool that is the root OS pool.  I will have to look at this.  I think OMVModuleZFSFilesystem::getAllFilesystems shouldn't be returning the root OS pool OR it is returning something other than '/' for the mountpoint.  This won't be a high priority since this is such a pain to setup a test and very few are using zfs for root.

**Comment by drgrandios** [comment]
>  It will return 0 (false) for any mountpoint that starts with / and not import it. 

The original fix didn't check the mountpoint but the filesystem name instead!

The input of getAllFilesystems looks similar to this format:
```
bpool	/boot
bpool/BOOT	none
bpool/BOOT/debian	/boot
data	/data
rpool	/
rpool/ROOT	none
rpool/ROOT/debian	/
rpool/home	/home
rpool/home/root	/root
rpool/usr	/usr
rpool/usr/local	/usr/local
rpool/var	/var
rpool/var/lib	/var/lib
rpool/var/log	/var/log
rpool/var/spool	/var/spool
```

I guess the author wanted to filter the filesystems without '/' - which works in this case as none of them can start with '/'

**Comment by ryecoaaron** [comment]
> The original fix didn't check the mountpoint but the filesystem name instead!

I missed that difference but checking that the mountpoint isn't / is better in my opinion.  Although /boot should be excluded too.

> I guess the author wanted to filter the filesystems without '/' - which works in this case as none of them can start with '/'

We don't want that though.  We want to try to import all non-root (and boot) pools.

**Comment by ryecoaaron** [comment]
I think getAllFilesystems in /usr/share/omvzfs/Filesystem.php should run this command:

`zfs list -p -o name,mountpoint -t filesystem | awk '$2 != "/" && $2 != "/boot" { print $0 }'`

If you want to return the other line you changed and change this one for a test, that would be great.

**Comment by drgrandios** [comment]
@ryecoaaron Seems to work, this is my diff of `/usr/share/omvzfs/Filesystem.php`:

```
50c50,51
< 		$cmd = "zfs list -p -H -o name,mountpoint -t filesystem";
---
> 		//$cmd = "zfs list -p -H -o name,mountpoint -t filesystem";
> 		$cmd = "zfs list -p -H -o name,mountpoint -t filesystem | awk '$2 != \"/\" && $2 != \"/boot\" { print $0 }'";

```

Looks quite similar and the "unique" error is still gone:

![grafik](https://user-images.githubusercontent.com/28082191/221266539-efa98d6d-39ca-4d8c-9a13-01eba487fa72.png)

A bit offtopic: I'm coming from OMV 4, which had a tree view that looked a lot cleaner and not that chaotic as it looks now:

![grafik](https://user-images.githubusercontent.com/28082191/221266830-f9d7ba62-69b3-4f5a-9cf2-2c663eac62c2.png)

Is there a way to enable such a view again?

**Comment by ryecoaaron** [comment]
> A bit offtopic: I'm coming from OMV 4, which had a tree view that looked a lot cleaner and not that chaotic as it looks now:  Is there a way to enable such a view again?

Nope.   Pre-omv6 had a custom extjs to create that.  With OMV 6, I have to use whatever is available in the omv framework.  The new code is much easier to maintain as well.

**Comment by Ciccius81** [comment]
> I think getAllFilesystems in /usr/share/omvzfs/Filesystem.php should run this command:
> 
> `zfs list -p -o name,mountpoint -t filesystem | awk '$2 != "/" && $2 != "/boot" { print $0 }'`
> 
> If you want to return the other line you changed and change this one for a test, that would be great.

Hi @ryecoaaron , @drgrandios , I am on OVM6 installed on fresh Debian 11 with boot and root partitions in zfs.
I did this edit but in ZFS plugin page, as soon it loads, it keep saying "mountpoint is not unique" regardless I removed the <mntent> section. Every time I remove <mntent> section OMV recreate it with a different UUID.
This error do not let me do anything (eg. import pools, new pool, etc...)

There is a procedure to do that edit? Am I missing something?
Thanks

**Comment by drgrandios** [comment]
@Ciccius81 Just checked... OMV had updated the ZFS plugin somewhen in the past so my change was gone and the installation broken again. I re-did the change to Filesystem.php and rebooted the server (quick solution.. maybe its okay to just restart some processes). Just reloading the web page was not enough!

Now it works for me again.

**Comment by ryecoaaron** [comment]
Changing the file is not enough.  You have to restart omv-engined or reboot.

I changed the plugin and will push an update when I have time.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/f4e96074b486e7629c1b6ba3d5a979fc8f072cb0

**Comment by Ciccius81** [comment]
@ryecoaaron @drgrandios 
Thanks you both, I was missing the restart of service/reboot, now it works!

**Comment by ryecoaaron** [comment]
This is pushed to the repo.
