### ISSUE TITLE
OMV3, openmediavault-zfs: Shared folders going n/a following ZFS pool export

### ISSUE THREAD

**Issue by kalleyne** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#39]
Posting from another group with recommendations from the moderator.

There seems to be a general problem where ZFS pool export results in the resetting of Shared folders to n/a devices. Importation of the pool does not correct the n/a status of devices on Shared folders. SMB clients are affected by this.

There was a discussion about this general issue on this thread:
https://forum.openmediavault.org/index.php/Thread/20364-Shared-folders-going-N-A-for-device-corrupts-USB-Backup/?postID=158505#post158505

https://forum.openmediavault.org/index.php/Thread/19861-How-to-correct-shared-folders-going-N-A-for-device-after-ZFS-unmount-remount-Can/

https://forum.openmediavault.org/index.php/Thread/17848-All-shared-folders-lost-Shows-up-as-n-a/

Please let me know if you require additional information.
Thanks.

**Comment by subzero79** [comment]
This fix will be either:
- Disable the export button when the pool is referenced. This implies adding to the backend service/method to return if pool is referenced. 
- remove the export button an use the unmount button of fs section. This is easier as the backend returns if the fs is referenced. We only need to override the unmount method that Omv provides. 

But do not expect that we can fix the behavior as exporting and reimporting will avoid sf not to break.

**Comment by ryecoaaron** [comment]
Closing due to age.
