### ISSUE TITLE
ZFS pool creation on the LUKS devices

### ISSUE THREAD

**Issue by artiomn** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#41]
I can't create ZFS pool on top of LUKS devices, using the plugin interface: devices doesn't appear in the list.
After the manually pool creation, plugin works fine with them.

**Comment by ryecoaaron** [comment]
Is the  LUKS device unlocked?  I can see dm-0 (my LUKS device) in the zfs plugin on my test system.  The naming could be better but it is there.

**Comment by artiomn** [comment]
I have tried to repeat. The problem arose, because I have created luks devices by hands and didn't click "Save configuration" on the yellow bar.
False alarm.
