### ISSUE TITLE
Remove spl from OMV Repo

### ISSUE THREAD

**Issue by Skaronator** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#44]
@ryecoaaron

Could you remove the spl version from the OMV Repo? It doesn't update my SPL version since it prefer the OMV Repo over the Backports.

```
root@OMV-NAS:~# apt-cache policy spl
spl:
  Installiert:           0.7.4-1
  Installationskandidat: 0.7.4-1
  Versionstabelle:
     0.7.6-1~bpo9+1 100
        100 http://httpredir.debian.org/debian stretch-backports/main amd64 Packages
 *** 0.7.4-1 500
        500 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-testing stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     0.7.3-1 500
        500 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-testing stretch/main amd64 Packages
     0.6.5.9-1 500
        500 http://ftp.de.debian.org/debian stretch/main amd64 Packages

```

**Comment by ryecoaaron** [comment]
This really won't help you since it will just prefer the debian 0.6.5.9-1 version then.  The backports version needs to be pinned or manually installed.  You can disable the omv-extras testing repo to test this.

$ sudo apt-cache policy spl
spl:
  Installed: (none)
  Candidate: 0.6.5.9-1
  Version table:
     0.7.6-1~bpo9+1 100
        100 http://httpredir.debian.org/debian stretch-backports/main amd64 Packages
     0.6.5.9-1 500
        500 http://cosmos.cites.illinois.edu/pub/debian stretch/main amd64 Packages

**Comment by ryecoaaron** [comment]
This has been fixed in the omv-extras package itself.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/commit/790834e023c3ef081dd1687f7cfb5a96fdba3a54
