### ISSUE TITLE
addPool RPC tries to created a zpool even if "by-id" or "by-path" device search silently fails

### ISSUE THREAD

**Issue by mdziekon** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#51]
Tested using:
* ``openmediavault``: 4.1.11
* ``openmediavault-zfs``: 4.0.4

Consider the following scenario:
1. You have an encrypted device (eg. using LUKS), assigned to ``/dev/dm-0`` device
2. Try to create a zpool using this device (a basic pool will be fine), and use the "by-id" or "by-path" dev aliasing
3. Since ``/dev/dm-0`` does not have a proper "by-path" aliasing (path is assigned to the disk rather than the encrypted container), and "by-id" aliasing fails (because ``OMVModuleZFSUtil::getDiskId`` does not accept dashes in device names), both silently, the ``$disks`` array in ``OMVRpcServiceZFS::addPool`` is empty.
4. Since disks mapping failed silently, ``addPool`` method is still trying to create the pool (it even created GPT labels already), which will fail because there are no vdevs.
5. Even though the pool creation has failed, the selected device already has a GPT label, which prevents us from using this drive again to create a pool (the device has to be wiped manually).

What should happen:
- The GPT labels should be created **after** it has been ensured that all devices can be properly aliased
- The pool creation should fail if at least one device was not properly aliased

Additional note:
- It appears that there is already a "fallback mechanism" that should prevent this situation from happening (it should fallback to "No aliasing" option), however, since both ``getDiskId`` and ``getDiskPath`` fail silently, it does not work at all. But to be honest, I'm not sure if it's a good idea to use that fallback at all - when creating the pool, it is explicitly selected to use one of the aliasing methods, so I'm not sure if silently selecting a fallback option is wise (this fallback uses the slightly non-deterministic way of selecting devices, for example consider the situation when for some reason a user will accidentally swap SATA cables leading to wrong device being used in zpool). When choosing "by-id" aliasing, I'm expecting this to be "by-id", not something else. But if for some reason it is desider to still have that fallback, maybe an "opt-in" checkbox would be enough?
- I'm willing to submit a patch for this issue myself, however I would like to hear maintainers response on my previous note (about the fallback option) before I start working on this.

**Comment by ryecoaaron** [comment]
Closing due to age.
