### ISSUE TITLE
Update translations for all plugins

### ISSUE THREAD

**Issue by ghost** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#55]
Hi,
I have translated many of the OMV plugins on Transifex. When will the translations be merged? I think some of the plugins are seldom updated. Will they ever get the translation updates?

Kind regards
Jonatan

**Comment by ryecoaaron** [comment]
I usually update the translations when I release an update.  But, I usually don't release an update for only translations.  Are there specific plugins you are interested in?

**Comment by jony0008** [comment]
openmediavault-anacron
 openmediavault-backup 
I'm done with these:
openmediavault-btsync 
openmediavault-calibre 
openmediavault-cups 
openmediavault-downloader 
openmediavault-extplorer 
openmediavault-fail2ban 
openmediavault-flashmemory 
openmediavault-git 
openmediavault-syncthing

**Comment by jony0008** [comment]
Please archive those that are no longer maintained in Transifex. I don't want anybody to make the same mistake. Thanks.

**Comment by ryecoaaron** [comment]
I didn't delete them from transifex in case they helped other plugins with similar translations and I thought someone might start maintaining them.  I don't see any way to archive on transifex.  So, if you don't see any value in them being there, I will delete them.

**Comment by jony0008** [comment]
I think you can decide better than me.
