### ISSUE TITLE
When will ZFS on Linux (ZoL) 0.8.0 be implemented in the plugin?

### ISSUE THREAD

**Issue by jdrch** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#56]
Not really an issue here, just a question. I'm considering using OMV for a headless server, but I also need ZFS and the [device evacuation/removal feature in ZoL v0.8.0](https://github.com/zfsonlinux/zfs/pull/6900). Ergo, I'm wondering when the latter will be integrated into the plugin. No pressure or demand, BTW ... just need to know so I'm aware of when I can expect OMV to be a viable solution for my needs. Thanks!

**Comment by ryecoaaron** [comment]
OMV 5.x should be able to use the proxmox 6.x kernel which has zfs 0.8.1.  The plugin probably won't have the features for zfs 0.8.x but you can use them from the command line.

**Comment by jdrch** [comment]
Fascinating, thanks!

**Comment by mdPlusPlus** [comment]
Is this still the recommended way of getting ZFS 0.8.x on OMV?

**Comment by MiguelNdeCarvalho** [comment]
Hey,
I know that this is an old issue, but I am sending the current version of ZFS here and I hope that you can close the issue.
![image](https://user-images.githubusercontent.com/33462772/90504804-86e15d00-e149-11ea-9433-fe164dec6469.png)
Thanks,
MiguelNdeCarvalho
