### ISSUE TITLE
Enable zfs plugin for ARMv7 architecture

### ISSUE THREAD

**Issue by awehrfritz** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#65]
Are there any plans, or would it be possible at all, to enable the zfs plugin for the ARMv7 (32-bit) architecture?

As far as I can tell, the zfs plugin is currently only available for the [amd64](https://bintray.com/beta/#/openmediavault-plugin-developers/usul/openmediavault-zfs?tab=overview) architecture. However, with the [release of ZFS 0.7.0](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.0) back in July 2017 and the introduction of [ARC Buffer Data (ABD)](https://github.com/zfsonlinux/zfs/commit/7657defc48b7c47a8bf0c8f21c78783d293dc5ed) there isn't much of a reason anymore for ZFS not to work on 32-bit platforms.

In particular, I have a [Helios4](https://wiki.kobol.io/helios4/intro/) NAS, which essentially is a Marvell Armada 388 SOC (ARMv7 32-bit) with 2 GB ECC RAM and up to 4 disks, and I use ZFS as filesystem for my data.

**Comment by ryecoaaron** [comment]
Until the Helios4 (and coming Helios64) and Rock Pro 64, it didn't make any sense to have the plugin available for arm boards.  I have a Rock Pro 64 and a Helios64 coming.  I will see what it takes to make this available.

**Comment by awehrfritz** [comment]
Great, thanks!

Just for your reference, I am currently running Armbian 19.11.3 Buster with Linux 4.19.84 and ZFS version 0.7.12 on my Helios4. ZFS version 0.8.2 from the buster-backports repo does not seem to work on this architecture at the moment, for some more details regarding this error and the ZFS installation see [this post in the Armbian forums](https://forum.armbian.com/topic/11526-zfs-on-helios4/?tab=comments#comment-91523).

You may also be interested in [this post](https://forum.armbian.com/topic/11526-zfs-on-helios4/page/2/?tab=comments#comment-94024) where I summarise some of the settings discussed in that thread regarding the usage of virtual address space in ZFS, in particular on 32-bit arm platforms.

**Comment by ryecoaaron** [comment]
I don't have a good way to test but it is in all of the support architectures now (amd64, i386, armhf, arm64).  Unfortunately, there are way too many head packages to list for arm boards.  So, you will most likely have to install the proper linux-headers for you board and kernel in order for zfs-dkms to compile the module.

The plugin doesn't make any system setting changes.  That would be a nightmare like the kernel headers to maintain.  So, those will require manual changes as well.

**Comment by awehrfritz** [comment]
Great, thanks for getting this done so quickly.

Just for reference in case somebody else stumbles across this, I installed ZFS for the stock kernel in Armbian 19.11.3 Buster on my Helios4. The package for that kernel is `linux-image-current-mvebu` and the kernel version is 4.19.84. The respective headers can be installed via the `linux-headers-current-mvebu` package.

It took me quite some trials to get this all right, so I put my installation routine into a script: [install_zfs_helios4.sh](https://gist.github.com/awehrfritz/533dcc6cb59ef8f753b1840fdaeef9aa)

**Comment by awehrfritz** [comment]
Just to quickly follow up on this: I had some issues with the kernel headers, even though I had the correct headers and image installed already (I had zfs installed already before I installed omv).

I reckon the issue with the headers is even worse on Armbian than on upstream Debian, since there are many custom kernel images and no meta package to get the correct headers automatically installed (at least not that I would know of).

Here the steps with which I finally got it installed:
``` sh
apt-get install zfs-zed
apt-get download openmediavault-zfs
dpkg --ignore-depends=linux-headers-amd64 -i openmediavault-zfs_5.0.3_all.deb
```
With this, the plugin shows up in the omv web-interface and appears to be working. Probably fine for now ...

**Comment by ryecoaaron** [comment]
I would like to make the headers optional for the dependency but then it wouldn't install them on amd64 and i386 systems.  If I make the dependency arch specific then I would have to build a version of the plugin for each arch.  I will have to look at other options for the dependency string.

**Comment by ryecoaaron** [comment]
This is better now.  The package is built for each supported architecture.  The armhf and arm64 packages have no kernel header dependencies.  The use will have to install them on armhf and arm64.  I can't think of a better way to improve this.

**Comment by awehrfritz** [comment]
Yes, this is much better now! I just tested this and on my system where I had zfs, together with the correct kernel headers, already installed. Installing the omv-zfs plugin via the web-interface works now as expected.

Installing the correct kernel headers on these Armbian systems is actually not overly difficult, even for inexperienced users, when resorting to the `armbian-config` utility. They have worked it out somehow to pick the correct headers for the respective kernel image.

Thanks for fixing this!

**Comment by ryecoaaron** [comment]
Either of the following one-liners work for most armbian installs:

[ ! "${BRANCH}" = "default" ] && branch="-${BRANCH}"; sudo apt-get install linux-headers${branch}-${LINUXFAMILY}

sudo apt-get install $(dpkg -l | grep linux-image | cut -d" " -f3 | sed "s/image/headers/")
