### ISSUE TITLE
How to build deb?

### ISSUE THREAD

**Issue by procount** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#67]
I'm trying to build this plugin myself (running on Ubuntu 14.04) so I can make a small amendment, but I'm unfamiliar with building deb files.

I downloaded the release tarball, and from within the openmedia-zfs-3.0.6 folder I ran
`fakeroot debian/rules clean binary`

But it doesn't seem to build. Here is the output:
```
kevin@ubuntu ~/openmediavault-zfs-3.0.6 $ fakeroot debian/rules clean binary
dh_testdir
dh_testroot
dh_clean
dh_testdir
dh_testroot
dh_prep
dh_installdirs
dh_install
Use of uninitialized value $dh{"FIRSTPACKAGE"} in string eq at /usr/bin/dh_install line 145.
dh_testdir
echo "Removing SCM files ..." >&2
Removing SCM files ...
find /home/kevin/openmediavault-zfs-3.0.6/debian/openmediavault-zfs-3.0.6 \( -name .svn -o -name .git \) \
	  -type d -print0 -prune | xargs -0r rm -rf
find: ‘/home/kevin/openmediavault-zfs-3.0.6/debian/openmediavault-zfs-3.0.6’: No such file or directory
dh_testdir
dh_testroot
dh_installchangelogs
dh_installdebconf
dh_lintian
dh_link
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
```
It was also missing a debian/files file (?) I created a blank one, but is there supposed to be something in there? Where can I find the resultant deb file?

Thanks for some guidance.

**Comment by ryecoaaron** [comment]
Your version of ubuntu is too old.  And why are you building such an old version of the plugin?

**Comment by procount** [comment]
Ah ok. What's the minimum version of Ubuntu I need? I'll spin up a new one.
I just picked the latest version from releases and didn't notice it was from 2016!
I guess I need to take the latest commit.

Or is there an easier way to do what I want - I just need to remove some dependencies. Can I just download the deb, edit the control file and zip it back up again? Where is the location of the latest deb file to download for OMV5?

**Comment by ryecoaaron** [comment]
Ideally you would build on Debian which is what OMV uses.  OMV 5 is Debian 10.

What dependencies and why?

**Comment by procount** [comment]
Probably easiest to read my post here -> https://forum.openmediavault.org/index.php/Thread/31103-Installing-OMV5-on-Raspberry-Pi4-with-ZFS/?postID=230117#post230123

**Comment by ryecoaaron** [comment]
See my response.  You don't need to change the dependencies.

**Comment by procount** [comment]
I managed to build the latest deb from source and removed the dependencies, so I was able to install the OMV plugin without the zfs-dks modules and install it manually. It seems to work with my prebuilt zfs modules, so we'll see how things go...
Thanks.
