### ISSUE TITLE
Installation of zfs extensions throws excessive "ERROR....." messages [SOLVED. See inside]

### ISSUE THREAD

**Issue by Wikinaut** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#68]
I have no idea what happens, but installation fails with "<<< ERROR" messages coming up. I have no idea, how to fetch that log file (perhaps you can help me?).

* OMV is up-to-date:
![grafik](https://user-images.githubusercontent.com/1151915/78774968-c5922a00-7995-11ea-9533-ff151b2b873c.png)

![grafik](https://user-images.githubusercontent.com/1151915/78774897-a398a780-7995-11ea-8dca-14ac0927513d.png)

**Comment by Wikinaut** [comment]
```
sudo apt install zfsutils-linux
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Vorgeschlagene Pakete:
  zfs-initramfs | zfs-dracut
Empfohlene Pakete:
  zfs-modules | zfs-dkms zfs-zed
Die folgenden NEUEN Pakete werden installiert:
  zfsutils-linux
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 290 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 1.087 kB Plattenplatz zusätzlich benutzt.
Vormals nicht ausgewähltes Paket zfsutils-linux wird gewählt.
(Lese Datenbank ... 85822 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../zfsutils-linux_0.7.12-2+deb10u1~bpo9+1_amd64.deb ...
Entpacken von zfsutils-linux (0.7.12-2+deb10u1~bpo9+1) ...
zfsutils-linux (0.7.12-2+deb10u1~bpo9+1) wird eingerichtet ...
Job for zfs-mount.service failed because the control process exited with error code.
See "systemctl status zfs-mount.service" and "journalctl -xe" for details.
invoke-rc.d: initscript zfs-mount, action "start" failed.
● zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/lib/systemd/system/zfs-mount.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-04-08 12:46:32 CEST; 4ms ago
     Docs: man:zfs(8)
  Process: 16878 ExecStart=/sbin/zfs mount -a (code=exited, status=1/FAILURE)
 Main PID: 16878 (code=exited, status=1/FAILURE)

Apr 08 12:46:32 nas10 systemd[1]: Starting Mount ZFS filesystems...
Apr 08 12:46:32 nas10 zfs[16878]: The ZFS modules are not loaded.
Apr 08 12:46:32 nas10 zfs[16878]: Try running '/sbin/modprobe zfs' as root to load them.
Apr 08 12:46:32 nas10 systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Apr 08 12:46:32 nas10 systemd[1]: Failed to start Mount ZFS filesystems.
Apr 08 12:46:32 nas10 systemd[1]: zfs-mount.service: Unit entered failed state.
Apr 08 12:46:32 nas10 systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
dpkg: Fehler beim Bearbeiten des Paketes zfsutils-linux (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 1 zurück
Trigger für systemd (232-25+deb9u12) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 zfsutils-linux
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f13ae4e57b8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f13ae4e57b8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Wikinaut** [comment]
Solved by applying the commands on the command line:

```
sudo apt instal zfs-dkms <<< important
sudo apt install zfsutils-linux
sudo modprobe zfs
```

and then restarted the installation of the extension.

**Comment by ryecoaaron** [comment]
And the plugin has zfs-dkms as a dependency - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/blob/master/debian/control#L20

If you use the proxmox kernel as most recommend, this issue is avoided since the zfs module is pre-compiled.  There is nothing the plugin can do to fix the zfs compilation issues since this work happens in the zfs packages not the plugin.  All the plugin can do is require them as a dependency.

**Comment by Wikinaut** [comment]
No idea what you mean by proxmox kernel. I use the standard OMV installation which I keep up to date.

**Comment by Wikinaut** [comment]
By the way, as explained, installation worked only after I had performed the above steps **manually**. So there might be a small issue you or your friends have overlooked, perhaps a "chicken-egg-issue"?

**Comment by ryecoaaron** [comment]
> No idea what you mean by proxmox kernel. I use the standard OMV installation which I keep up to date.

omv-extras has a kernel tab where you can install the Proxmox kernel.  This is the kernel used by proxmox that has zfs support.  It is actually Ubuntu's kernel and very stable.

> By the way, as explained, installation worked only after I had performed the above steps manually. So there might be a small issue you or your friends have overlooked, perhaps a "chicken-egg-issue"?

I understand how you fixed and what causes it.  What I am saying is that the plugin can't fix it.  There is nothing we have overlooked.  The zfs-dkms package (not the plugin) is delicate and if you don't have the right kernel and kernel headers installed, it will fail to compile.  There is no feasible way to make sure in a debian control file that the correct headers are installed for every available kernel.
