### ISSUE TITLE
Ghost child fs after changing the mountpoint of the root fs of a pool

### ISSUE THREAD

**Issue by gouarfig** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#7]
While playing with ZFS I encountered this bug:
- Create a datapool, named tank, and leave its root file system mounted on **/tank**
- Create a file system in it, named test1, and leave it mounted on **/tank/test1**
- Change the mountpoint of the root fs to something else, in my case **/mnt/tank**
  _I wanted to change the mountpoint of the root. I looked at the properties of the pool and it wasn't there. So I did it manually_
  `zfs set mountpoint=/mnt/tank tank`
- The mountpoint of the child is automatically moved to **/mnt/tank/test1** by inheritance, it's all fine.

**BUG**: The previous mountpoint of test1 **/tank/test1** keeps reappearing, even after deleting manually.
- Delete the child fs test1
- Apply the configuration

**BUG**: OMV complains that it can't find **/tank/test1** in either fstab or mtab.
- I had to manually delete a reference of it in /etc/openmediavault/config.xml
## Proposal
1. I think the GUI should present the mountpoint property in the list of the root properties, so we know we can change it there
2. It should delete the previous references of all the children FS in OMV

**Comment by nicjo814** [comment]
First of all I must say this was a really good bug report (the other ones too). Unfortunately though I have very limited time to actually work with the plug-in which means that I probably won't be able to address any of the issues in the coming weeks. I'll make a new comment here with my thoughts on the actual issues when I feel that I can focus on this a bit more. 
If you want to you are very welcome to look at the code and submit a PR. 
Sorry for not being able to do any more at the moment.

**Comment by gouarfig** [comment]
I know what you mean, I have the exact same problem... lack of time. I suppose I could have a look at the code, but that's another thing to add to my list and delay everything else so I'd better not, at least not now. Also it's not urgent.

I do think OMV works at its best with ZFS (as the real Linux counterpart of FreeNas) while waiting for btrfs to be production ready; then the choice between both will be difficult :-)

Thanks for the great work so far!

**Comment by ryecoaaron** [comment]
Closing due to age.
