### ISSUE TITLE
Error after importing existing ZFS pool renders ZFS tab unusable

### ISSUE THREAD

**Issue by larb0b** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#71]
I moved from a base Debian install to OpenMediaVault (fresh install). I installed OpenMediaVault-ZFS and tried to import my pool but had errors as ZFS was installed without backports. I upgraded ZFS to the version from buster-backports and it's able to import fine, but I'm unable to use the ZFS tab in the OMV web GUI:

```
Error #0:
OMV\AssertException: The configuration object 'conf.system.filesystem.mountpoint' is not unique. An object with the property 'dir' and value '/krini' already exists. in /usr/share/php/openmediavault/config/database.inc:495
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/fstab.inc(121): OMV\Config\Database->assertIsUnique(Object(OMV\Config\ConfigObject), 'dir')
#1 [internal function]: Engined\Rpc\FsTab->set(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('set', Array, Array)
#4 /usr/share/omvzfs/Utils.php(217): OMV\Rpc\Rpc::call('FsTab', 'set', Array, Array)
#5 /usr/share/openmediavault/engined/rpc/zfs.inc(186): OMVModuleZFSUtil::fixOMVMntEnt(Array)
#6 [internal function]: OMVRpcServiceZFS->getObjectTree(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getObjectTree', Array, Array)
#9 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ZFS', 'getObjectTree', Array, Array, 1)
#10 {main}
```

I have tried to delete the entry within OMV's config and importing through the ZFS tab but no matter what I have this error.

**Comment by subzero79** [comment]
There is somehow a duplicate entry on the db. This gets complicated as you probably have shared folders associated with the pool. I think is better if you import the pool in cli instead of using the webui.

**Comment by larb0b** [comment]
I tried deleting the only entry I found with the mountpoint and then adding it again through the UI to no avail. I have everything set up now so I guess I'll just have a broken ZFS tab...

**Comment by subzero79** [comment]
Whats the error now? is the same as before?
Also is the pool imported already?

Another question are all the shared folders dependant on the root pool file system or they depend on other child datasets of the pool?

**Comment by ryecoaaron** [comment]
Closing due to age.
