### ISSUE TITLE
Snapshot sorting only gets applied per page

### ISSUE THREAD

**Issue by ralphscheu** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#72]
First of all huge thanks for this amazing plugin! I've encountered a minor UX bug that caused me some confusion before I figured out what was going on.

**Situation**:
I keep 30 daily snapshots around at any time, which means that 5 of them get moved to a second page in the Snapshot Overview since it defaults to 25 per page. If I now e.g. sort descending by name (they are named after ISO-8601) so the most recent day goes to the top, the sorting only includes the 25 snapshots on the first page. To me, it now looks like my most recent snapshot is 5  days old.

*EDIT: added two screenshots to clarify*
![omvzfs_snapshot_issue1](https://user-images.githubusercontent.com/3540420/85444505-ad907680-b592-11ea-93c7-868779c3543b.png)
![omvzfs_snapshot_issue2](https://user-images.githubusercontent.com/3540420/85444514-b08b6700-b592-11ea-8fe4-924932551213.png)

**Expected result**:
I would expect the sorting of snapshots in the overview to get applied across all items, and for the sorted items to get paginated thereafter. Right now it looks like sorting only happens after items got paginated into chunks of 25.

This is obviously not a huge deal, but it is not the correct behaviour in my opinion and might be a relatively quick fix.
I'd be willing to submit a PR, but am no JS guy so it would take me some time to understand the OMV codebase and UI framework.

Cheers

**Comment by ryecoaaron** [comment]
Closing due to age.
