### ISSUE TITLE
Suggest adding recommend parameter by default when create new pool

### ISSUE THREAD

**Issue by alphaarea** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#73]
The recommend parameters will improve proformance and compatibility.
And it doesn‘t seem to have any negative effects.

Reference:
[Openzfs Docs
Debian Buster Root on ZFS
Step 2: Disk Formatting](https://openzfs.github.io/openzfs-docs/Getting%20Started/Debian/Debian%20Buster%20Root%20on%20ZFS.html?highlight=relatime#step-2-disk-formatting)
| property | value |
| ----------- | ------- |
| ashift | 12 |
| acltype | posixacl |
| compression | lz4 |
| dnodesize | auto |
| normalization | formD |
| relatime | on |
| xattr | sa |

**Comment by ryecoaaron** [comment]
Most of these have been added in the latest release.
