### ISSUE TITLE
Communication error: relax timeout for slow setup

### ISSUE THREAD

**Issue by sneumann** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#74]
Hi, for training purposes I run OMV5 (5.5.19-1) on kvm with 3 USB thumb drives in raidz.
In this setup I get `Communication error` in the webgui. `zpool status` and `zpool list` work fine 
on the command line, and in `top` I can see zfs kernel stuff going on, so things look fine.

=> Is there a way (at least for debugging ?) to increase the timeout value that causes the `Communication error`.

Yours,
Steffen

**Comment by ryecoaaron** [comment]
Sorry, that is a core OMV hard coded setting.

**Comment by sneumann** [comment]
Indeed, I found https://forum.openmediavault.org/index.php?thread/11260-omv-web-gui-timeout-too-low-or-s-m-a-r-t-issue/ and some hacking fixed / worked around my issue. Thx, Yours, Steffen
