### ISSUE TITLE
OMV 6 release?

### ISSUE THREAD

**Issue by Niemand112233** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#75]
Hi,

when will this plugin be available on OMV 6?

**Comment by ryecoaaron** [comment]
No idea.  I haven't ported most of the plugins and this will be the worst one to port since the web interface portion will have to be completely re-thought out.

**Comment by Niemand112233** [comment]
thx for the fast reply. So if I would like to use ZFS I would need to go with OMV 5, right? Or can I just install the Debian ZFS-Package?

**Comment by ryecoaaron** [comment]
There is no zfs backend if the plugin is not installed.  So, you can't use zfs in the web interface without the backend.

I highly recommend not using OMV 6.x yet.

**Comment by Niemand112233** [comment]
Ok. Will it be possible to Upgrade to 6 from 5?

**Comment by ryecoaaron** [comment]
Should be just like all previous versions.

**Comment by Niemand112233** [comment]
Thx!
