### ISSUE TITLE
Snapshot information not available in OMV 6.x

### ISSUE THREAD

**Issue by huangwb8** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#77]
After installing OMV 6.x, I found ZFS snapshot information is not available in GUI.

There's only limited information, such as type, available space, status, et.al.

Is it normal? Would the interact be improved in the future?

**Comment by ryecoaaron** [comment]
What other info are you looking for?  The 6.x plugin has the exact same snapshot that the 5.x plugin has.

**Comment by huangwb8** [comment]
@ryecoaaron 
Thanks! Now everything is OK.

I think it's nothing about zfs. It's new OMV version or Chrome cache that result in the delayed appearance of the ZFS button.

I logged in just now and found the ZFS button had appeared. As you say, it's the same as 5.x plugin.
