### ISSUE TITLE
Filesystem "false" after import ZFS pools

### ISSUE THREAD

**Issue by g2ufo** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#78]
Latest OMV 6.0.8-1 (Shaitan) and latest zfs plugin with proxmox kernel.
Filesystem "false" after import ZFS pools.
But all pools is OK and share work fine
![Screenshot_1](https://user-images.githubusercontent.com/51451549/149511340-c815d810-560d-49de-8514-f5ba7fdf5cba.jpg)

**Comment by ryecoaaron** [comment]
I am able to reproduce this.  I will note that it does not cause any problems other than not showing the device in the Filesystems tab.

**Comment by ryecoaaron** [comment]
Fix in latest commit.  I will release this after I add another feature.  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/commit/a8bf3276914bc0c18858091950c7c018b89c9631
