### ISSUE TITLE
Make sure the mount point is empty when creating a new filesystem

### ISSUE THREAD

**Issue by gouarfig** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#8]
How to reproduce the bug:
- Create a new child filesystem and specify a mountpoint where some files or folders are already in place.
- The command will fail stating that you can't mount the filesystem there because the mounpoint is not empty.

_But behind the scene, the filesystem has been created with the default mountpoint._
- When you try to create it again, it silently only changes the mounpoint, but not removes the default mountpoint from the OMV database. Then you can't apply the configuration because it keeps failing. The only solution is to remove the reference directly in /etc/openmediavault/config.xml

Easy fix:
I think the GUI should check the mountpoint is empty before creating the filesystem.

**Comment by ryecoaaron** [comment]
Closing due to age.
