### ISSUE TITLE
Drives dont show up 

### ISSUE THREAD

**Issue by TimyIsCool** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#88]
![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/assets/74112751/93807116-e786-4bec-941d-c6818dc87e58)
No drives show up here. One has been wiped and one hasn't, would think at least one shows up

**Comment by ryecoaaron** [comment]
Are they USB drives?  USB drives are not support for mdadm or zfs in OMV.

**Comment by TimyIsCool** [comment]
Hard drives connected via usb
Is there a way to bypass it?

**Comment by ryecoaaron** [comment]
Not for creation.  You can create the zpool from the command line and the plugin will show it.

**Comment by TimyIsCool** [comment]
How would I do it in command line?

**Comment by ryecoaaron** [comment]
Any guide for Debian and ZFS on the internet should work.  There is a reason OMV doesn't allow raid on usb.  It is a bad idea.

**Comment by TimyIsCool** [comment]
Got it working, thank you
