### ISSUE TITLE
Add direct support for xattr and acltype in File System properties

### ISSUE THREAD

**Issue by gouarfig** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#9]
I noticed the performance of ZFS through SAMBA were absolutely terrible. Browsing big folders from a Windows machine was taking seconds.

After reading a lot of documentation about it, and trying out things, I managed to get it working as fast as a Windows file server could be:

You need to tweak both properties called **xattr** and **acltype**

Here are a few links about it:
https://github.com/zfsonlinux/zfs/issues/170
http://www.nerdblog.com/2013/10/zfs-xattr-tuning-on-linux.html

I managed to change these settings by adding a new property from the GUI, but that would be nice to have a specific parameter when you create a file system (or edit it).

Thanks!

**Comment by ryecoaaron** [comment]
Closing due to age and these default properties have been changed recently.  You can also edit them in the Properties editor.
