### ISSUE TITLE
Disks keep disconnecting

### ISSUE THREAD

**Issue by TimyIsCool** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#90]
Hi, So I know USB drives aren't supported but when I run them solo with EXT4 on OMV the drives work fine for days on end
But with ZFS the drives disconnect after minutes or hours and needs a full reboot before showing again

**Comment by ryecoaaron** [comment]
Since usb isn't supported, this isn't something I have ever tested.  It isn't something caused by the plugin.  All I can guess is that zfs doesn't handle the drives going to sleep.

**Comment by TimyIsCool** [comment]
is there a way to prevent the disks from going to sleep?

**Comment by ryecoaaron** [comment]
Depends on the controller but for most, no. And I am just guessing that is the issue.

**Comment by TimyIsCool** [comment]
So I tried this and it seemed to have worked for the time being anyways
(Running a Pi4 8GB with debian and a usb ssd disk)

`sudo nano /etc/udev/rules.d/99-usb-disks.rules`

add in the line
`ACTION=="add", SUBSYSTEM=="block", RUN+="/sbin/sdparm --clear STANDBY /dev/sda"`
(Change the /dev/sda to the disk you dont want sleeping. And I believe change it to hdpram for HDD's but thats a guess)

Then finally run 
`sudo udevadm control --reload-rules`
to reload it and it should now not go to sleep!

**Comment by TimyIsCool** [comment]
Well
Was fine until I hit it with a load, then it just disconnected

**Comment by ellnic** [comment]
Perhaps try the solution I suggested? 🤷‍♂️

**Comment by TimyIsCool** [comment]
So i got a different adaptor with a different controller it seems to work, but the other one works sometimes so its why I was confused but in the end I got something working 
Im running ZFS so when I can afford something like a microserver I can move my ZFS drives and should just work

**Comment by ryecoaaron** [comment]
n100 systems with sata ports are almost cheaper than rpi setups after buying usb adapter

**Comment by TimyIsCool** [comment]
I just had a pi and some adapters layong around from previous projects so thats why I used it
