### ISSUE TITLE
Make it Compatible to newer Kernels. PLS

### ISSUE THREAD

**Issue by crazybanane** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#93]
Can you please make the Plugin compatible to newer Kernel´s above 6.2?
There is a newer Version for ZFS availlable to support kernel´s "zfs-2.2.4"

**Comment by ryecoaaron** [comment]
The plugin has nothing to do with this.  It is dependent on the version of zfs in the debian repos.  If you look [here](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=zfs-zed), you can see that zfs 2.2.4 is already in debian backports.  You can enable/disable backports in omv-extras.
