### ISSUE TITLE
delete dataset should not delete non-empty folder

### ISSUE THREAD

**Issue by clouds56** [OpenMediaVault-Plugin-Developers/openmediavault-zfs#95]
consider we have zpool `test` mounted at `/test` with files like this
```shell
$ mkdir -p test/aaa/bb
$ tree /test/aaa
/test/aaa
└── bb

2 directories, 0 files
```
I add a `FileSystem` named `test/aaa` and destroy it, if I do it in cli using command, it would keep `/test/aaa/bb` as is.
```
$ zfs create test/aaa
$ tree test/aaa
/test/aaa

0 directories, 0 files
$ zfs destroy test/aaa
tree /test/aaa           
/test/aaa
└── bb

2 directories, 0 files
```
but if I do it in UI, the whole folder `aaa` and `aaa/bb` would also be deleted. It's so DANGEROUS, I mean to delete a dataset, but never mean to delete files in parent dataset.
I think we should do `rmdir aaa`, but not `rm -rf aaa` here in `deleteObject`.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/blob/ba70575d9404232798a82859eb319b400cd558c3/usr/share/openmediavault/engined/rpc/zfs.inc#L381-L388

**Comment by ryecoaaron** [comment]
Where do you see a rm -rf?  deleteOMVMntEnt deletes the [fstab entry](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-zfs/blob/ba70575d9404232798a82859eb319b400cd558c3/usr/share/omvzfs/Utils.php#L78) and that just unmounts and deletes the database entry using core OMV code - https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/engined/rpc/fstab.inc#L154

**Comment by ryecoaaron** [comment]
I don't know why or how you create a filesystem if test/aaa/bb already exists.  It makes sense to me that bb would be deleted if aaa filesystem went away.  Even non-zfs filesystems would do that.  Otherwise, you couldn't access bb because it would be under the aaa mountpoint.

**Comment by clouds56** [comment]
It might be by mistake, I upload my photos to `/data/Photos`, and then I realize I should create a dataset for it.
And I mistakenly create a dataset named `data/Photos` (the same name), now I cannot find my photos (it still in dataset `data`, but just I cannot find it).
So I decided to delete the dataset `data/Photos` I created just now, if I go with `zfs destroy data/Photos`, things are just ok, I got my photos back, but if I click the UI, my photos would really deleted.

By the way, any filesystem when you mount/umount a dev, it would never delete the underlying folder IIRC.

**Comment by clouds56** [comment]
Yes, I'm the stupid one just delete my home folder with all settings.

**Comment by ryecoaaron** [comment]
OMV is cleaning up the mountpoint which I don't think is wrong.  Otherwise, the system could end up with a lot of empty directories.  I'm not sure what to do here but I don't think this is a zfs plugin issue.  I need to test to see if this is done with all filesystem types.  I also need to find the code where OMV is cleaning up the mountpoint.

**Comment by clouds56** [comment]
> I also need to find the code where OMV is cleaning up the mountpoint.
It's here. Yes that's not a zfs plugin issue here, maybe we should warn user when creating a dataset at an non-empty folder.

https://github.com/openmediavault/openmediavault/blob/80aa6d7ff99e35a157cdf9dd7ebd1cb5908c5595/deb/openmediavault/usr/share/openmediavault/engined/module/fstab.inc#L79

**Comment by clouds56** [comment]
```php
	/**
	 * Unlink the mountpoint of the file system.
	 * @param force Set to TRUE to ignore nonexistent files. Defaults to TRUE.
	 * @return void
	 * @throw \OMV\ExecException
	 */
	public function unlink($force = TRUE) {
		// Exit immediately if the directory doesn't exists.
		if (FALSE === $this->exists())
			return;
		$cmdArgs = [];
		$cmdArgs[] = "--recursive";
		if (TRUE === $force) {
			$cmdArgs[] = "--force";
		}
		$cmdArgs[] = escapeshellarg($this->getPath());
		$cmd = new \OMV\System\Process("rm", $cmdArgs);
		$cmd->setRedirect2to1();
		$cmd->execute();
	}
```
